version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --http-port=8180
    ports:
      - "8180:8180"
    networks:
      - mynetwork

  auth-api-demo:
    image: anacondong/auth-api-demo
    depends_on:
      - keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_URL: http://keycloak:8180
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
