spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/quickstart/protocol/openid-connect/certs

config:
  auth:
    server:  ${KEYCLOAK_URL:http://localhost:8180}
